alter table specs add column  brands_name varchar(64) default null,
      add column price int not null default 0,
      add column level int not null default 0,
      add column displacement int not null default 0,
      add column seat_num int not null default 0,
      add column structure int not null default 0,
      add column energy int not null default 0,
      add column gbox int not null default 0,
      add column skylight int not null default 0,
      add column e_contr_seat int not null default 0,
      add column gps int not null default 0,
      add column esp int not null default 0,
      add column hid int not null default 0,
      add column leather_seat int not null default 0,
      add column dlcc int not null default 0,
      add column auto_air_cond int not null default 0,
      add column revers_img int not null default 0,
      add column keyless_go int not null default 0,
      add column seat_heat int not null default 0,
      add column auto_park int not null default 0,
      add column intake_mode int not null default 0,
      add column drive_mode int not null default 0;

