
update specs set brands_name = "东风风度" , price =135500 ,price_grade=2, grade=3 , displacement =3 , seat_num=3 ,struct=0 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =0 , esp =1 ,hid=0 , leather_seat=0 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=0 , auto_park=0 , intake_mode=1 ,drive_mode=1 where id =24820;
update specs set brands_name = "标志" , price =279700 ,price_grade=4, grade=4 , displacement =3 , seat_num=5 ,struct=0 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=1 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=1 , auto_park=0 , intake_mode=2 ,drive_mode=1 where id =28723;
update specs set brands_name = "东风风光" , price =123000 ,price_grade=2, grade=4 , displacement =2 , seat_num=5 ,struct=0 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=0 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=0 , auto_park=0 , intake_mode=2 ,drive_mode=1 where id =30199;
update specs set brands_name = "长安" , price =119900 ,price_grade=2, grade=9 , displacement =2 , seat_num=5 ,struct=0 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=0 , dlcc =1 , auto_air_cond=0 , revers_img=1 , keyless_go=1 ,seat_heat=1 , auto_park=0 , intake_mode=2 ,drive_mode=1 where id =30204;
update specs set brands_name = "沃尔沃" , price =937800 ,price_grade=7, grade=5 , displacement =3 , seat_num=5 ,struct=0 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=1 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=1 , auto_park=1 , intake_mode=2 ,drive_mode=3 where id =31001;
update specs set brands_name = "斯柯达" , price =249800 ,price_grade=4, grade=4 , displacement =3 , seat_num=3 ,struct=3 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=1 , leather_seat=1 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=1 , auto_park=1 , intake_mode=2 ,drive_mode=1 where id =31790;
update specs set brands_name = "众泰" , price =139900 ,price_grade=2, grade=4 , displacement =3 , seat_num=3 ,struct=0 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=0 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=1 , auto_park=0 , intake_mode=2 ,drive_mode=1 where id =31819;
update specs set brands_name = "斯柯达" , price =269800 ,price_grade=4, grade=4 , displacement =3 , seat_num=5 ,struct=0 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=1 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=1 , auto_park=1 , intake_mode=2 ,drive_mode=3 where id =32102;
update specs set brands_name = "捷豹" , price =288800 ,price_grade=4, grade=4 , displacement =3 , seat_num=3 ,struct=2 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =0 , esp =1 ,hid=1 , leather_seat=1 , dlcc =1 , auto_air_cond=1 , revers_img=0 , keyless_go=1 ,seat_heat=0 , auto_park=0 , intake_mode=2 ,drive_mode=2 where id =32611;
update specs set brands_name = "奔驰" , price =1776800 ,price_grade=8, grade=5 , displacement =6 , seat_num=3 ,struct=2 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=1 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=1 , auto_park=1 , intake_mode=2 ,drive_mode=3 where id =32776;
update specs set brands_name = "宝马" , price =585800 ,price_grade=6, grade=4 , displacement =3 , seat_num=3 ,struct=0 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=1 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=1 , auto_park=1 , intake_mode=2 ,drive_mode=3 where id =33229;
update specs set brands_name = "大众" , price =359800 ,price_grade=5, grade=4 , displacement =3 , seat_num=3 ,struct=0 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=1 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=1 , auto_park=1 , intake_mode=2 ,drive_mode=3 where id =33341;
update specs set brands_name = "长安" , price =105900 ,price_grade=2, grade=3 , displacement =2 , seat_num=3 ,struct=2 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=0 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=0 , auto_park=0 , intake_mode=1 ,drive_mode=1 where id =33393;
update specs set brands_name = "标志" , price =273700 ,price_grade=4, grade=3 , displacement =3 , seat_num=3 ,struct=0 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=1 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=1 , auto_park=0 , intake_mode=2 ,drive_mode=1 where id =33445;
update specs set brands_name = "本田" , price =199800 ,price_grade=3, grade=4 , displacement =2 , seat_num=3 ,struct=2 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =0 , esp =1 ,hid=0 , leather_seat=0 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=0 , auto_park=1 , intake_mode=2 ,drive_mode=1 where id =34200;
update specs set brands_name = "比亚迪" , price =119900 ,price_grade=2, grade=9 , displacement =2 , seat_num=5 ,struct=0 , energy=1 , gbox =2 , skylight=1 , e_contr_seat=1 , gps =1 , esp =1 ,hid=0 , leather_seat=0 , dlcc =1 , auto_air_cond=1 , revers_img=1 , keyless_go=1 ,seat_heat=0 , auto_park=0 , intake_mode=2 ,drive_mode=1 where id =34353;

